version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "dev"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "mysqluser"
      # You can use whatever password you like
      MYSQL_PASSWORD: "mysql"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1.schema.sql
# Names our volume
# volumes:
#   my-db:
